### ISSUE TITLE
Request for Feature: How to close all opened Realm Instances

### ISSUE THREAD

**Issue by Drjacky** [Zhuinden/realm-helpers#12]
There is a `closeLocalInstance` in `RealmManager` and of course, it caught exception if there isn't any open Realm:  
```javascript
if(realm == null || realm.isClosed()) {
            throw new IllegalStateException(
                    "Cannot close a Realm that is not open.");
        }
```
Anyway, how to close all opened Realm Instances by calling just one method?
One of its usages is when we're going to use `Realm.deleteRealm()`; We have to close all instances before calling this, [otherwise](https://stackoverflow.com/a/37648877/421467), an exception will be thrown without deleting anything.

**Comment by Zhuinden** [comment]
It would be possible to force close Realm on a thread with

     while(!realm.isClosed()) {
          realm.close();
      }

But then you might need some failsafe code where you expect Realm to be open but isn't.

**Comment by Drjacky** [comment]
Thank you, but how to prevent such this problem? Is it possible to handle it in a way that requests for closing the open Realm instances and waiting for them to do their jobs?

You know, I think it's a simple request from a  Manager(`RealmManager`) to handle such this; Request for remove whole Data, but wait for open Realm instances to finish their jobs.

**Comment by Zhuinden** [comment]
You see, the tricky part isn't waiting for Realm instances to finish jobs because they are thread-local, the tricky part is that if you initialize your views in `onCreate()` which I usually do, then you'll only reset them when the Activity is recreated.

Or if you implement a "reset" for your RealmResults and stuff (in your adapters, for example)

So this isn't something I can do, but it's burden on whoever wants to close Realms they are using.

**Comment by Drjacky** [comment]
Agreed :white_check_mark:
